---
title: "TZ SNP Scatter"
author: "Hannah Koenker"
date: "11/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(haven)
library(janitor)
library(wesanderson)
library(ggthemes)
pal <-  wes_palette(9, name = "Zissou1", type = "continuous")
```

```{r}
snp <- read_dta("snp_scatter.dta") %>% 
  clean_names()
```

```{r}
snp %>% 
  ggplot(aes(accrk, percpop,
            color = as.factor(snp))) +
  geom_point() +
  theme_minimal() +
  scale_color_manual(values = pal) 

# +
#   stat_smooth(data = snp, aes(accrk, percpop), se = FALSE)
  
  # theme(legend.title = element_blank()) +
#  scale_color_brewer(palette = "Dark2")
theme_

snp %>% 
  ggplot(aes(accrk, percpop)) +
  geom_point() +
  scale_color_manual() +
  stat_smooth(, se = FALSE)

```

```{r}
ggplot(snp, aes(x = accrk, y = percpop, color = as.factor(snp), alpha = 0.5)) +
  geom_point() +
  scale_alpha(guide = "none") +
  scale_color_pander() +
  theme_classic() +
  labs(color="SNP") +
  geom_smooth(data = snp, aes(x = accrk, y = percpop), se = FALSE, inherit.aes = FALSE, method = "loess", color = "steelblue", span = 1)
```

